import type { Job } from './jobs.schema'

/**
 * In-memory jobs dataset — read-only seed loaded at startup (A1 Decision 5:
 * sanctioned tech debt; production would be a database). 96 deterministic
 * rows (stable ids `job-01`..`job-96`) so tests can pin exact records.
 *
 * Coverage: 16 rows (~17%) have `salary: null`; `publishedAt` spans
 * distinct ISO datetimes so date sorts are meaningful; cities cover the MX set
 * (Ciudad de México, Guadalajara, Monterrey, Puebla, Querétaro, Tijuana, Mérida, León, Cancún, Remoto). At `limit=20` this yields 5 pages.
 */
export const jobs: Job[] = [
  {
    id: 'job-01',
    title: 'React Native Developer',
    company: 'OCC Mundial',
    city: 'Ciudad de México',
    salary: null,
    description:
      'Buscamos React Native Developer para unirse al equipo de OCC Mundial en Ciudad de México. Trabajarás con React Native, TypeScript, Mobile en proyectos de alto impacto.',
    publishedAt: '2025-09-01T00:00:00.000Z',
    tags: ['React Native', 'TypeScript', 'Mobile'],
  },
  {
    id: 'job-02',
    title: 'Frontend Engineer Jr',
    company: 'Nubank MX',
    city: 'Guadalajara',
    salary: 25000,
    description:
      'Buscamos Frontend Engineer Jr para unirse al equipo de Nubank MX en Guadalajara. Trabajarás con React, TypeScript, CSS en proyectos de alto impacto.',
    publishedAt: '2025-10-02T01:07:00.000Z',
    tags: ['React', 'TypeScript', 'CSS'],
  },
  {
    id: 'job-03',
    title: 'Backend Engineer Semi Senior',
    company: 'Kavak',
    city: 'Monterrey',
    salary: 115000,
    description:
      'Buscamos Backend Engineer Semi Senior para unirse al equipo de Kavak en Monterrey. Trabajarás con Node.js, Express, PostgreSQL en proyectos de alto impacto.',
    publishedAt: '2025-11-03T02:14:00.000Z',
    tags: ['Node.js', 'Express', 'PostgreSQL'],
  },
  {
    id: 'job-04',
    title: 'Full Stack Developer Senior',
    company: 'Bitso',
    city: 'Puebla',
    salary: 150000,
    description:
      'Buscamos Full Stack Developer Senior para unirse al equipo de Bitso en Puebla. Trabajarás con React, Node.js, TypeScript en proyectos de alto impacto.',
    publishedAt: '2025-12-04T03:21:00.000Z',
    tags: ['React', 'Node.js', 'TypeScript'],
  },
  {
    id: 'job-05',
    title: 'Mobile Engineer iOS Staff',
    company: 'Clip',
    city: 'Querétaro',
    salary: 135000,
    description:
      'Buscamos Mobile Engineer iOS Staff para unirse al equipo de Clip en Querétaro. Trabajarás con Swift, iOS, Mobile en proyectos de alto impacto.',
    publishedAt: '2026-01-05T04:28:00.000Z',
    tags: ['Swift', 'iOS', 'Mobile'],
  },
  {
    id: 'job-06',
    title: 'Mobile Engineer Android',
    company: 'Konfío',
    city: 'Tijuana',
    salary: 75000,
    description:
      'Buscamos Mobile Engineer Android para unirse al equipo de Konfío en Tijuana. Trabajarás con Kotlin, Android, Mobile en proyectos de alto impacto.',
    publishedAt: '2026-02-06T05:35:00.000Z',
    tags: ['Kotlin', 'Android', 'Mobile'],
  },
  {
    id: 'job-07',
    title: 'DevOps Engineer Jr',
    company: 'Clara',
    city: 'Mérida',
    salary: null,
    description:
      'Buscamos DevOps Engineer Jr para unirse al equipo de Clara en Mérida. Trabajarás con AWS, Docker, Kubernetes en proyectos de alto impacto.',
    publishedAt: '2026-03-07T06:42:00.000Z',
    tags: ['AWS', 'Docker', 'Kubernetes'],
  },
  {
    id: 'job-08',
    title: 'Data Engineer Semi Senior',
    company: 'Jüsto',
    city: 'León',
    salary: 125000,
    description:
      'Buscamos Data Engineer Semi Senior para unirse al equipo de Jüsto en León. Trabajarás con Python, Spark, SQL en proyectos de alto impacto.',
    publishedAt: '2026-04-08T07:49:00.000Z',
    tags: ['Python', 'Spark', 'SQL'],
  },
  {
    id: 'job-09',
    title: 'QA Automation Engineer Senior',
    company: 'Rappi',
    city: 'Cancún',
    salary: 135000,
    description:
      'Buscamos QA Automation Engineer Senior para unirse al equipo de Rappi en Cancún. Trabajarás con Cypress, Jest, Testing en proyectos de alto impacto.',
    publishedAt: '2026-05-09T08:56:00.000Z',
    tags: ['Cypress', 'Jest', 'Testing'],
  },
  {
    id: 'job-10',
    title: 'UX/UI Designer Staff',
    company: 'Mercado Libre',
    city: 'Remoto',
    salary: 110000,
    description:
      'Buscamos UX/UI Designer Staff para unirse al equipo de Mercado Libre en Remoto. Trabajarás con Figma, Design, Prototyping en proyectos de alto impacto.',
    publishedAt: '2026-06-10T09:03:00.000Z',
    tags: ['Figma', 'Design', 'Prototyping'],
  },
  {
    id: 'job-11',
    title: 'Product Manager',
    company: 'Softtek',
    city: 'Ciudad de México',
    salary: 40000,
    description:
      'Buscamos Product Manager para unirse al equipo de Softtek en Ciudad de México. Trabajarás con Product, Agile, Roadmap en proyectos de alto impacto.',
    publishedAt: '2025-09-11T10:10:00.000Z',
    tags: ['Product', 'Agile', 'Roadmap'],
  },
  {
    id: 'job-12',
    title: 'Engineering Manager Jr',
    company: 'Globant',
    city: 'Guadalajara',
    salary: 90000,
    description:
      'Buscamos Engineering Manager Jr para unirse al equipo de Globant en Guadalajara. Trabajarás con Leadership, Agile, Hiring en proyectos de alto impacto.',
    publishedAt: '2025-10-12T11:17:00.000Z',
    tags: ['Leadership', 'Agile', 'Hiring'],
  },
  {
    id: 'job-13',
    title: 'Machine Learning Engineer Semi Senior',
    company: 'Wizeline',
    city: 'Monterrey',
    salary: null,
    description:
      'Buscamos Machine Learning Engineer Semi Senior para unirse al equipo de Wizeline en Monterrey. Trabajarás con Python, TensorFlow, ML en proyectos de alto impacto.',
    publishedAt: '2025-11-13T12:24:00.000Z',
    tags: ['Python', 'TensorFlow', 'ML'],
  },
  {
    id: 'job-14',
    title: 'Cloud Architect Senior',
    company: 'Belatrix',
    city: 'Puebla',
    salary: 55000,
    description:
      'Buscamos Cloud Architect Senior para unirse al equipo de Belatrix en Puebla. Trabajarás con AWS, Azure, Architecture en proyectos de alto impacto.',
    publishedAt: '2025-12-14T13:31:00.000Z',
    tags: ['AWS', 'Azure', 'Architecture'],
  },
  {
    id: 'job-15',
    title: 'Security Engineer Staff',
    company: 'Encora',
    city: 'Querétaro',
    salary: 30000,
    description:
      'Buscamos Security Engineer Staff para unirse al equipo de Encora en Querétaro. Trabajarás con Security, Pentesting, IAM en proyectos de alto impacto.',
    publishedAt: '2026-01-15T14:38:00.000Z',
    tags: ['Security', 'Pentesting', 'IAM'],
  },
  {
    id: 'job-16',
    title: 'Site Reliability Engineer',
    company: 'OCC Mundial',
    city: 'Tijuana',
    salary: 85000,
    description:
      'Buscamos Site Reliability Engineer para unirse al equipo de OCC Mundial en Tijuana. Trabajarás con SRE, Monitoring, Kubernetes en proyectos de alto impacto.',
    publishedAt: '2026-02-16T15:45:00.000Z',
    tags: ['SRE', 'Monitoring', 'Kubernetes'],
  },
  {
    id: 'job-17',
    title: 'Technical Lead Jr',
    company: 'Nubank MX',
    city: 'Mérida',
    salary: 40000,
    description:
      'Buscamos Technical Lead Jr para unirse al equipo de Nubank MX en Mérida. Trabajarás con Leadership, React, Node.js en proyectos de alto impacto.',
    publishedAt: '2026-03-17T16:52:00.000Z',
    tags: ['Leadership', 'React', 'Node.js'],
  },
  {
    id: 'job-18',
    title: 'Data Scientist Semi Senior',
    company: 'Kavak',
    city: 'León',
    salary: 150000,
    description:
      'Buscamos Data Scientist Semi Senior para unirse al equipo de Kavak en León. Trabajarás con Python, Statistics, ML en proyectos de alto impacto.',
    publishedAt: '2026-04-18T17:59:00.000Z',
    tags: ['Python', 'Statistics', 'ML'],
  },
  {
    id: 'job-19',
    title: 'React Native Developer Senior',
    company: 'Bitso',
    city: 'Cancún',
    salary: null,
    description:
      'Buscamos React Native Developer Senior para unirse al equipo de Bitso en Cancún. Trabajarás con React Native, TypeScript, Mobile en proyectos de alto impacto.',
    publishedAt: '2026-05-19T18:06:00.000Z',
    tags: ['React Native', 'TypeScript', 'Mobile'],
  },
  {
    id: 'job-20',
    title: 'Frontend Engineer Staff',
    company: 'Clip',
    city: 'Remoto',
    salary: 95000,
    description:
      'Buscamos Frontend Engineer Staff para unirse al equipo de Clip en Remoto. Trabajarás con React, TypeScript, CSS en proyectos de alto impacto.',
    publishedAt: '2026-06-20T19:13:00.000Z',
    tags: ['React', 'TypeScript', 'CSS'],
  },
  {
    id: 'job-21',
    title: 'Backend Engineer',
    company: 'Konfío',
    city: 'Ciudad de México',
    salary: 45000,
    description:
      'Buscamos Backend Engineer para unirse al equipo de Konfío en Ciudad de México. Trabajarás con Node.js, Express, PostgreSQL en proyectos de alto impacto.',
    publishedAt: '2025-09-21T20:20:00.000Z',
    tags: ['Node.js', 'Express', 'PostgreSQL'],
  },
  {
    id: 'job-22',
    title: 'Full Stack Developer Jr',
    company: 'Clara',
    city: 'Guadalajara',
    salary: 60000,
    description:
      'Buscamos Full Stack Developer Jr para unirse al equipo de Clara en Guadalajara. Trabajarás con React, Node.js, TypeScript en proyectos de alto impacto.',
    publishedAt: '2025-10-22T21:27:00.000Z',
    tags: ['React', 'Node.js', 'TypeScript'],
  },
  {
    id: 'job-23',
    title: 'Mobile Engineer iOS Semi Senior',
    company: 'Jüsto',
    city: 'Monterrey',
    salary: 55000,
    description:
      'Buscamos Mobile Engineer iOS Semi Senior para unirse al equipo de Jüsto en Monterrey. Trabajarás con Swift, iOS, Mobile en proyectos de alto impacto.',
    publishedAt: '2025-11-23T22:34:00.000Z',
    tags: ['Swift', 'iOS', 'Mobile'],
  },
  {
    id: 'job-24',
    title: 'Mobile Engineer Android Senior',
    company: 'Rappi',
    city: 'Puebla',
    salary: 50000,
    description:
      'Buscamos Mobile Engineer Android Senior para unirse al equipo de Rappi en Puebla. Trabajarás con Kotlin, Android, Mobile en proyectos de alto impacto.',
    publishedAt: '2025-12-24T23:41:00.000Z',
    tags: ['Kotlin', 'Android', 'Mobile'],
  },
  {
    id: 'job-25',
    title: 'DevOps Engineer Staff',
    company: 'Mercado Libre',
    city: 'Querétaro',
    salary: null,
    description:
      'Buscamos DevOps Engineer Staff para unirse al equipo de Mercado Libre en Querétaro. Trabajarás con AWS, Docker, Kubernetes en proyectos de alto impacto.',
    publishedAt: '2026-01-25T00:48:00.000Z',
    tags: ['AWS', 'Docker', 'Kubernetes'],
  },
  {
    id: 'job-26',
    title: 'Data Engineer',
    company: 'Softtek',
    city: 'Tijuana',
    salary: 55000,
    description:
      'Buscamos Data Engineer para unirse al equipo de Softtek en Tijuana. Trabajarás con Python, Spark, SQL en proyectos de alto impacto.',
    publishedAt: '2026-02-26T01:55:00.000Z',
    tags: ['Python', 'Spark', 'SQL'],
  },
  {
    id: 'job-27',
    title: 'QA Automation Engineer Jr',
    company: 'Globant',
    city: 'Mérida',
    salary: 75000,
    description:
      'Buscamos QA Automation Engineer Jr para unirse al equipo de Globant en Mérida. Trabajarás con Cypress, Jest, Testing en proyectos de alto impacto.',
    publishedAt: '2026-03-27T02:02:00.000Z',
    tags: ['Cypress', 'Jest', 'Testing'],
  },
  {
    id: 'job-28',
    title: 'UX/UI Designer Semi Senior',
    company: 'Wizeline',
    city: 'León',
    salary: 110000,
    description:
      'Buscamos UX/UI Designer Semi Senior para unirse al equipo de Wizeline en León. Trabajarás con Figma, Design, Prototyping en proyectos de alto impacto.',
    publishedAt: '2026-04-01T03:09:00.000Z',
    tags: ['Figma', 'Design', 'Prototyping'],
  },
  {
    id: 'job-29',
    title: 'Product Manager Senior',
    company: 'Belatrix',
    city: 'Cancún',
    salary: 40000,
    description:
      'Buscamos Product Manager Senior para unirse al equipo de Belatrix en Cancún. Trabajarás con Product, Agile, Roadmap en proyectos de alto impacto.',
    publishedAt: '2026-05-02T04:16:00.000Z',
    tags: ['Product', 'Agile', 'Roadmap'],
  },
  {
    id: 'job-30',
    title: 'Engineering Manager Staff',
    company: 'Encora',
    city: 'Remoto',
    salary: 125000,
    description:
      'Buscamos Engineering Manager Staff para unirse al equipo de Encora en Remoto. Trabajarás con Leadership, Agile, Hiring en proyectos de alto impacto.',
    publishedAt: '2026-06-03T05:23:00.000Z',
    tags: ['Leadership', 'Agile', 'Hiring'],
  },
  {
    id: 'job-31',
    title: 'Machine Learning Engineer',
    company: 'OCC Mundial',
    city: 'Ciudad de México',
    salary: null,
    description:
      'Buscamos Machine Learning Engineer para unirse al equipo de OCC Mundial en Ciudad de México. Trabajarás con Python, TensorFlow, ML en proyectos de alto impacto.',
    publishedAt: '2025-09-04T06:30:00.000Z',
    tags: ['Python', 'TensorFlow', 'ML'],
  },
  {
    id: 'job-32',
    title: 'Cloud Architect Jr',
    company: 'Nubank MX',
    city: 'Guadalajara',
    salary: 125000,
    description:
      'Buscamos Cloud Architect Jr para unirse al equipo de Nubank MX en Guadalajara. Trabajarás con AWS, Azure, Architecture en proyectos de alto impacto.',
    publishedAt: '2025-10-05T07:37:00.000Z',
    tags: ['AWS', 'Azure', 'Architecture'],
  },
  {
    id: 'job-33',
    title: 'Security Engineer Semi Senior',
    company: 'Kavak',
    city: 'Monterrey',
    salary: 150000,
    description:
      'Buscamos Security Engineer Semi Senior para unirse al equipo de Kavak en Monterrey. Trabajarás con Security, Pentesting, IAM en proyectos de alto impacto.',
    publishedAt: '2025-11-06T08:44:00.000Z',
    tags: ['Security', 'Pentesting', 'IAM'],
  },
  {
    id: 'job-34',
    title: 'Site Reliability Engineer Senior',
    company: 'Bitso',
    city: 'Puebla',
    salary: 85000,
    description:
      'Buscamos Site Reliability Engineer Senior para unirse al equipo de Bitso en Puebla. Trabajarás con SRE, Monitoring, Kubernetes en proyectos de alto impacto.',
    publishedAt: '2025-12-07T09:51:00.000Z',
    tags: ['SRE', 'Monitoring', 'Kubernetes'],
  },
  {
    id: 'job-35',
    title: 'Technical Lead Staff',
    company: 'Clip',
    city: 'Querétaro',
    salary: 75000,
    description:
      'Buscamos Technical Lead Staff para unirse al equipo de Clip en Querétaro. Trabajarás con Leadership, React, Node.js en proyectos de alto impacto.',
    publishedAt: '2026-01-08T10:58:00.000Z',
    tags: ['Leadership', 'React', 'Node.js'],
  },
  {
    id: 'job-36',
    title: 'Data Scientist',
    company: 'Konfío',
    city: 'Tijuana',
    salary: 155000,
    description:
      'Buscamos Data Scientist para unirse al equipo de Konfío en Tijuana. Trabajarás con Python, Statistics, ML en proyectos de alto impacto.',
    publishedAt: '2026-02-09T11:05:00.000Z',
    tags: ['Python', 'Statistics', 'ML'],
  },
  {
    id: 'job-37',
    title: 'React Native Developer Jr',
    company: 'Clara',
    city: 'Mérida',
    salary: null,
    description:
      'Buscamos React Native Developer Jr para unirse al equipo de Clara en Mérida. Trabajarás con React Native, TypeScript, Mobile en proyectos de alto impacto.',
    publishedAt: '2026-03-10T12:12:00.000Z',
    tags: ['React Native', 'TypeScript', 'Mobile'],
  },
  {
    id: 'job-38',
    title: 'Frontend Engineer Semi Senior',
    company: 'Jüsto',
    city: 'León',
    salary: 45000,
    description:
      'Buscamos Frontend Engineer Semi Senior para unirse al equipo de Jüsto en León. Trabajarás con React, TypeScript, CSS en proyectos de alto impacto.',
    publishedAt: '2026-04-11T13:19:00.000Z',
    tags: ['React', 'TypeScript', 'CSS'],
  },
  {
    id: 'job-39',
    title: 'Backend Engineer Senior',
    company: 'Rappi',
    city: 'Cancún',
    salary: 60000,
    description:
      'Buscamos Backend Engineer Senior para unirse al equipo de Rappi en Cancún. Trabajarás con Node.js, Express, PostgreSQL en proyectos de alto impacto.',
    publishedAt: '2026-05-12T14:26:00.000Z',
    tags: ['Node.js', 'Express', 'PostgreSQL'],
  },
  {
    id: 'job-40',
    title: 'Full Stack Developer Staff',
    company: 'Mercado Libre',
    city: 'Remoto',
    salary: 120000,
    description:
      'Buscamos Full Stack Developer Staff para unirse al equipo de Mercado Libre en Remoto. Trabajarás con React, Node.js, TypeScript en proyectos de alto impacto.',
    publishedAt: '2026-06-13T15:33:00.000Z',
    tags: ['React', 'Node.js', 'TypeScript'],
  },
  {
    id: 'job-41',
    title: 'Mobile Engineer iOS',
    company: 'Softtek',
    city: 'Ciudad de México',
    salary: 150000,
    description:
      'Buscamos Mobile Engineer iOS para unirse al equipo de Softtek en Ciudad de México. Trabajarás con Swift, iOS, Mobile en proyectos de alto impacto.',
    publishedAt: '2025-09-14T16:40:00.000Z',
    tags: ['Swift', 'iOS', 'Mobile'],
  },
  {
    id: 'job-42',
    title: 'Mobile Engineer Android Jr',
    company: 'Globant',
    city: 'Guadalajara',
    salary: 110000,
    description:
      'Buscamos Mobile Engineer Android Jr para unirse al equipo de Globant en Guadalajara. Trabajarás con Kotlin, Android, Mobile en proyectos de alto impacto.',
    publishedAt: '2025-10-15T17:47:00.000Z',
    tags: ['Kotlin', 'Android', 'Mobile'],
  },
  {
    id: 'job-43',
    title: 'DevOps Engineer Semi Senior',
    company: 'Wizeline',
    city: 'Monterrey',
    salary: null,
    description:
      'Buscamos DevOps Engineer Semi Senior para unirse al equipo de Wizeline en Monterrey. Trabajarás con AWS, Docker, Kubernetes en proyectos de alto impacto.',
    publishedAt: '2025-11-16T18:54:00.000Z',
    tags: ['AWS', 'Docker', 'Kubernetes'],
  },
  {
    id: 'job-44',
    title: 'Data Engineer Senior',
    company: 'Belatrix',
    city: 'Puebla',
    salary: 55000,
    description:
      'Buscamos Data Engineer Senior para unirse al equipo de Belatrix en Puebla. Trabajarás con Python, Spark, SQL en proyectos de alto impacto.',
    publishedAt: '2025-12-17T19:01:00.000Z',
    tags: ['Python', 'Spark', 'SQL'],
  },
  {
    id: 'job-45',
    title: 'QA Automation Engineer Staff',
    company: 'Encora',
    city: 'Querétaro',
    salary: 70000,
    description:
      'Buscamos QA Automation Engineer Staff para unirse al equipo de Encora en Querétaro. Trabajarás con Cypress, Jest, Testing en proyectos de alto impacto.',
    publishedAt: '2026-01-18T20:08:00.000Z',
    tags: ['Cypress', 'Jest', 'Testing'],
  },
  {
    id: 'job-46',
    title: 'UX/UI Designer',
    company: 'OCC Mundial',
    city: 'Tijuana',
    salary: 35000,
    description:
      'Buscamos UX/UI Designer para unirse al equipo de OCC Mundial en Tijuana. Trabajarás con Figma, Design, Prototyping en proyectos de alto impacto.',
    publishedAt: '2026-02-19T21:15:00.000Z',
    tags: ['Figma', 'Design', 'Prototyping'],
  },
  {
    id: 'job-47',
    title: 'Product Manager Jr',
    company: 'Nubank MX',
    city: 'Mérida',
    salary: 80000,
    description:
      'Buscamos Product Manager Jr para unirse al equipo de Nubank MX en Mérida. Trabajarás con Product, Agile, Roadmap en proyectos de alto impacto.',
    publishedAt: '2026-03-20T22:22:00.000Z',
    tags: ['Product', 'Agile', 'Roadmap'],
  },
  {
    id: 'job-48',
    title: 'Engineering Manager Semi Senior',
    company: 'Kavak',
    city: 'León',
    salary: 100000,
    description:
      'Buscamos Engineering Manager Semi Senior para unirse al equipo de Kavak en León. Trabajarás con Leadership, Agile, Hiring en proyectos de alto impacto.',
    publishedAt: '2026-04-21T23:29:00.000Z',
    tags: ['Leadership', 'Agile', 'Hiring'],
  },
  {
    id: 'job-49',
    title: 'Machine Learning Engineer Senior',
    company: 'Bitso',
    city: 'Cancún',
    salary: null,
    description:
      'Buscamos Machine Learning Engineer Senior para unirse al equipo de Bitso en Cancún. Trabajarás con Python, TensorFlow, ML en proyectos de alto impacto.',
    publishedAt: '2026-05-22T00:36:00.000Z',
    tags: ['Python', 'TensorFlow', 'ML'],
  },
  {
    id: 'job-50',
    title: 'Cloud Architect Staff',
    company: 'Clip',
    city: 'Remoto',
    salary: 70000,
    description:
      'Buscamos Cloud Architect Staff para unirse al equipo de Clip en Remoto. Trabajarás con AWS, Azure, Architecture en proyectos de alto impacto.',
    publishedAt: '2026-06-23T01:43:00.000Z',
    tags: ['AWS', 'Azure', 'Architecture'],
  },
  {
    id: 'job-51',
    title: 'Security Engineer',
    company: 'Konfío',
    city: 'Ciudad de México',
    salary: 50000,
    description:
      'Buscamos Security Engineer para unirse al equipo de Konfío en Ciudad de México. Trabajarás con Security, Pentesting, IAM en proyectos de alto impacto.',
    publishedAt: '2025-09-24T02:50:00.000Z',
    tags: ['Security', 'Pentesting', 'IAM'],
  },
  {
    id: 'job-52',
    title: 'Site Reliability Engineer Jr',
    company: 'Clara',
    city: 'Guadalajara',
    salary: 75000,
    description:
      'Buscamos Site Reliability Engineer Jr para unirse al equipo de Clara en Guadalajara. Trabajarás con SRE, Monitoring, Kubernetes en proyectos de alto impacto.',
    publishedAt: '2025-10-25T03:57:00.000Z',
    tags: ['SRE', 'Monitoring', 'Kubernetes'],
  },
  {
    id: 'job-53',
    title: 'Technical Lead Semi Senior',
    company: 'Jüsto',
    city: 'Monterrey',
    salary: 100000,
    description:
      'Buscamos Technical Lead Semi Senior para unirse al equipo de Jüsto en Monterrey. Trabajarás con Leadership, React, Node.js en proyectos de alto impacto.',
    publishedAt: '2025-11-26T04:04:00.000Z',
    tags: ['Leadership', 'React', 'Node.js'],
  },
  {
    id: 'job-54',
    title: 'Data Scientist Senior',
    company: 'Rappi',
    city: 'Puebla',
    salary: 105000,
    description:
      'Buscamos Data Scientist Senior para unirse al equipo de Rappi en Puebla. Trabajarás con Python, Statistics, ML en proyectos de alto impacto.',
    publishedAt: '2025-12-27T05:11:00.000Z',
    tags: ['Python', 'Statistics', 'ML'],
  },
  {
    id: 'job-55',
    title: 'React Native Developer Staff',
    company: 'Mercado Libre',
    city: 'Querétaro',
    salary: null,
    description:
      'Buscamos React Native Developer Staff para unirse al equipo de Mercado Libre en Querétaro. Trabajarás con React Native, TypeScript, Mobile en proyectos de alto impacto.',
    publishedAt: '2026-01-01T06:18:00.000Z',
    tags: ['React Native', 'TypeScript', 'Mobile'],
  },
  {
    id: 'job-56',
    title: 'Frontend Engineer',
    company: 'Softtek',
    city: 'Tijuana',
    salary: 75000,
    description:
      'Buscamos Frontend Engineer para unirse al equipo de Softtek en Tijuana. Trabajarás con React, TypeScript, CSS en proyectos de alto impacto.',
    publishedAt: '2026-02-02T07:25:00.000Z',
    tags: ['React', 'TypeScript', 'CSS'],
  },
  {
    id: 'job-57',
    title: 'Backend Engineer Jr',
    company: 'Globant',
    city: 'Mérida',
    salary: 55000,
    description:
      'Buscamos Backend Engineer Jr para unirse al equipo de Globant en Mérida. Trabajarás con Node.js, Express, PostgreSQL en proyectos de alto impacto.',
    publishedAt: '2026-03-03T08:32:00.000Z',
    tags: ['Node.js', 'Express', 'PostgreSQL'],
  },
  {
    id: 'job-58',
    title: 'Full Stack Developer Semi Senior',
    company: 'Wizeline',
    city: 'León',
    salary: 120000,
    description:
      'Buscamos Full Stack Developer Semi Senior para unirse al equipo de Wizeline en León. Trabajarás con React, Node.js, TypeScript en proyectos de alto impacto.',
    publishedAt: '2026-04-04T09:39:00.000Z',
    tags: ['React', 'Node.js', 'TypeScript'],
  },
  {
    id: 'job-59',
    title: 'Mobile Engineer iOS Senior',
    company: 'Belatrix',
    city: 'Cancún',
    salary: 120000,
    description:
      'Buscamos Mobile Engineer iOS Senior para unirse al equipo de Belatrix en Cancún. Trabajarás con Swift, iOS, Mobile en proyectos de alto impacto.',
    publishedAt: '2026-05-05T10:46:00.000Z',
    tags: ['Swift', 'iOS', 'Mobile'],
  },
  {
    id: 'job-60',
    title: 'Mobile Engineer Android Staff',
    company: 'Encora',
    city: 'Remoto',
    salary: 70000,
    description:
      'Buscamos Mobile Engineer Android Staff para unirse al equipo de Encora en Remoto. Trabajarás con Kotlin, Android, Mobile en proyectos de alto impacto.',
    publishedAt: '2026-06-06T11:53:00.000Z',
    tags: ['Kotlin', 'Android', 'Mobile'],
  },
  {
    id: 'job-61',
    title: 'DevOps Engineer',
    company: 'OCC Mundial',
    city: 'Ciudad de México',
    salary: null,
    description:
      'Buscamos DevOps Engineer para unirse al equipo de OCC Mundial en Ciudad de México. Trabajarás con AWS, Docker, Kubernetes en proyectos de alto impacto.',
    publishedAt: '2025-09-07T12:00:00.000Z',
    tags: ['AWS', 'Docker', 'Kubernetes'],
  },
  {
    id: 'job-62',
    title: 'Data Engineer Jr',
    company: 'Nubank MX',
    city: 'Guadalajara',
    salary: 70000,
    description:
      'Buscamos Data Engineer Jr para unirse al equipo de Nubank MX en Guadalajara. Trabajarás con Python, Spark, SQL en proyectos de alto impacto.',
    publishedAt: '2025-10-08T13:07:00.000Z',
    tags: ['Python', 'Spark', 'SQL'],
  },
  {
    id: 'job-63',
    title: 'QA Automation Engineer Semi Senior',
    company: 'Kavak',
    city: 'Monterrey',
    salary: 75000,
    description:
      'Buscamos QA Automation Engineer Semi Senior para unirse al equipo de Kavak en Monterrey. Trabajarás con Cypress, Jest, Testing en proyectos de alto impacto.',
    publishedAt: '2025-11-09T14:14:00.000Z',
    tags: ['Cypress', 'Jest', 'Testing'],
  },
  {
    id: 'job-64',
    title: 'UX/UI Designer Senior',
    company: 'Bitso',
    city: 'Puebla',
    salary: 40000,
    description:
      'Buscamos UX/UI Designer Senior para unirse al equipo de Bitso en Puebla. Trabajarás con Figma, Design, Prototyping en proyectos de alto impacto.',
    publishedAt: '2025-12-10T15:21:00.000Z',
    tags: ['Figma', 'Design', 'Prototyping'],
  },
  {
    id: 'job-65',
    title: 'Product Manager Staff',
    company: 'Clip',
    city: 'Querétaro',
    salary: 120000,
    description:
      'Buscamos Product Manager Staff para unirse al equipo de Clip en Querétaro. Trabajarás con Product, Agile, Roadmap en proyectos de alto impacto.',
    publishedAt: '2026-01-11T16:28:00.000Z',
    tags: ['Product', 'Agile', 'Roadmap'],
  },
  {
    id: 'job-66',
    title: 'Engineering Manager',
    company: 'Konfío',
    city: 'Tijuana',
    salary: 125000,
    description:
      'Buscamos Engineering Manager para unirse al equipo de Konfío en Tijuana. Trabajarás con Leadership, Agile, Hiring en proyectos de alto impacto.',
    publishedAt: '2026-02-12T17:35:00.000Z',
    tags: ['Leadership', 'Agile', 'Hiring'],
  },
  {
    id: 'job-67',
    title: 'Machine Learning Engineer Jr',
    company: 'Clara',
    city: 'Mérida',
    salary: null,
    description:
      'Buscamos Machine Learning Engineer Jr para unirse al equipo de Clara en Mérida. Trabajarás con Python, TensorFlow, ML en proyectos de alto impacto.',
    publishedAt: '2026-03-13T18:42:00.000Z',
    tags: ['Python', 'TensorFlow', 'ML'],
  },
  {
    id: 'job-68',
    title: 'Cloud Architect Semi Senior',
    company: 'Jüsto',
    city: 'León',
    salary: 35000,
    description:
      'Buscamos Cloud Architect Semi Senior para unirse al equipo de Jüsto en León. Trabajarás con AWS, Azure, Architecture en proyectos de alto impacto.',
    publishedAt: '2026-04-14T19:49:00.000Z',
    tags: ['AWS', 'Azure', 'Architecture'],
  },
  {
    id: 'job-69',
    title: 'Security Engineer Senior',
    company: 'Rappi',
    city: 'Cancún',
    salary: 90000,
    description:
      'Buscamos Security Engineer Senior para unirse al equipo de Rappi en Cancún. Trabajarás con Security, Pentesting, IAM en proyectos de alto impacto.',
    publishedAt: '2026-05-15T20:56:00.000Z',
    tags: ['Security', 'Pentesting', 'IAM'],
  },
  {
    id: 'job-70',
    title: 'Site Reliability Engineer Staff',
    company: 'Mercado Libre',
    city: 'Remoto',
    salary: 150000,
    description:
      'Buscamos Site Reliability Engineer Staff para unirse al equipo de Mercado Libre en Remoto. Trabajarás con SRE, Monitoring, Kubernetes en proyectos de alto impacto.',
    publishedAt: '2026-06-16T21:03:00.000Z',
    tags: ['SRE', 'Monitoring', 'Kubernetes'],
  },
  {
    id: 'job-71',
    title: 'Technical Lead',
    company: 'Softtek',
    city: 'Ciudad de México',
    salary: 75000,
    description:
      'Buscamos Technical Lead para unirse al equipo de Softtek en Ciudad de México. Trabajarás con Leadership, React, Node.js en proyectos de alto impacto.',
    publishedAt: '2025-09-17T22:10:00.000Z',
    tags: ['Leadership', 'React', 'Node.js'],
  },
  {
    id: 'job-72',
    title: 'Data Scientist Jr',
    company: 'Globant',
    city: 'Guadalajara',
    salary: 70000,
    description:
      'Buscamos Data Scientist Jr para unirse al equipo de Globant en Guadalajara. Trabajarás con Python, Statistics, ML en proyectos de alto impacto.',
    publishedAt: '2025-10-18T23:17:00.000Z',
    tags: ['Python', 'Statistics', 'ML'],
  },
  {
    id: 'job-73',
    title: 'React Native Developer Semi Senior',
    company: 'Wizeline',
    city: 'Monterrey',
    salary: null,
    description:
      'Buscamos React Native Developer Semi Senior para unirse al equipo de Wizeline en Monterrey. Trabajarás con React Native, TypeScript, Mobile en proyectos de alto impacto.',
    publishedAt: '2025-11-19T00:24:00.000Z',
    tags: ['React Native', 'TypeScript', 'Mobile'],
  },
  {
    id: 'job-74',
    title: 'Frontend Engineer Senior',
    company: 'Belatrix',
    city: 'Puebla',
    salary: 45000,
    description:
      'Buscamos Frontend Engineer Senior para unirse al equipo de Belatrix en Puebla. Trabajarás con React, TypeScript, CSS en proyectos de alto impacto.',
    publishedAt: '2025-12-20T01:31:00.000Z',
    tags: ['React', 'TypeScript', 'CSS'],
  },
  {
    id: 'job-75',
    title: 'Backend Engineer Staff',
    company: 'Encora',
    city: 'Querétaro',
    salary: 75000,
    description:
      'Buscamos Backend Engineer Staff para unirse al equipo de Encora en Querétaro. Trabajarás con Node.js, Express, PostgreSQL en proyectos de alto impacto.',
    publishedAt: '2026-01-21T02:38:00.000Z',
    tags: ['Node.js', 'Express', 'PostgreSQL'],
  },
  {
    id: 'job-76',
    title: 'Full Stack Developer',
    company: 'OCC Mundial',
    city: 'Tijuana',
    salary: 45000,
    description:
      'Buscamos Full Stack Developer para unirse al equipo de OCC Mundial en Tijuana. Trabajarás con React, Node.js, TypeScript en proyectos de alto impacto.',
    publishedAt: '2026-02-22T03:45:00.000Z',
    tags: ['React', 'Node.js', 'TypeScript'],
  },
  {
    id: 'job-77',
    title: 'Mobile Engineer iOS Jr',
    company: 'Nubank MX',
    city: 'Mérida',
    salary: 85000,
    description:
      'Buscamos Mobile Engineer iOS Jr para unirse al equipo de Nubank MX en Mérida. Trabajarás con Swift, iOS, Mobile en proyectos de alto impacto.',
    publishedAt: '2026-03-23T04:52:00.000Z',
    tags: ['Swift', 'iOS', 'Mobile'],
  },
  {
    id: 'job-78',
    title: 'Mobile Engineer Android Semi Senior',
    company: 'Kavak',
    city: 'León',
    salary: 155000,
    description:
      'Buscamos Mobile Engineer Android Semi Senior para unirse al equipo de Kavak en León. Trabajarás con Kotlin, Android, Mobile en proyectos de alto impacto.',
    publishedAt: '2026-04-24T05:59:00.000Z',
    tags: ['Kotlin', 'Android', 'Mobile'],
  },
  {
    id: 'job-79',
    title: 'DevOps Engineer Senior',
    company: 'Bitso',
    city: 'Cancún',
    salary: null,
    description:
      'Buscamos DevOps Engineer Senior para unirse al equipo de Bitso en Cancún. Trabajarás con AWS, Docker, Kubernetes en proyectos de alto impacto.',
    publishedAt: '2026-05-25T06:06:00.000Z',
    tags: ['AWS', 'Docker', 'Kubernetes'],
  },
  {
    id: 'job-80',
    title: 'Data Engineer Staff',
    company: 'Clip',
    city: 'Remoto',
    salary: 75000,
    description:
      'Buscamos Data Engineer Staff para unirse al equipo de Clip en Remoto. Trabajarás con Python, Spark, SQL en proyectos de alto impacto.',
    publishedAt: '2026-06-26T07:13:00.000Z',
    tags: ['Python', 'Spark', 'SQL'],
  },
  {
    id: 'job-81',
    title: 'QA Automation Engineer',
    company: 'Konfío',
    city: 'Ciudad de México',
    salary: 125000,
    description:
      'Buscamos QA Automation Engineer para unirse al equipo de Konfío en Ciudad de México. Trabajarás con Cypress, Jest, Testing en proyectos de alto impacto.',
    publishedAt: '2025-09-27T08:20:00.000Z',
    tags: ['Cypress', 'Jest', 'Testing'],
  },
  {
    id: 'job-82',
    title: 'UX/UI Designer Jr',
    company: 'Clara',
    city: 'Guadalajara',
    salary: 30000,
    description:
      'Buscamos UX/UI Designer Jr para unirse al equipo de Clara en Guadalajara. Trabajarás con Figma, Design, Prototyping en proyectos de alto impacto.',
    publishedAt: '2025-10-01T09:27:00.000Z',
    tags: ['Figma', 'Design', 'Prototyping'],
  },
  {
    id: 'job-83',
    title: 'Product Manager Semi Senior',
    company: 'Jüsto',
    city: 'Monterrey',
    salary: 45000,
    description:
      'Buscamos Product Manager Semi Senior para unirse al equipo de Jüsto en Monterrey. Trabajarás con Product, Agile, Roadmap en proyectos de alto impacto.',
    publishedAt: '2025-11-02T10:34:00.000Z',
    tags: ['Product', 'Agile', 'Roadmap'],
  },
  {
    id: 'job-84',
    title: 'Engineering Manager Senior',
    company: 'Rappi',
    city: 'Puebla',
    salary: 60000,
    description:
      'Buscamos Engineering Manager Senior para unirse al equipo de Rappi en Puebla. Trabajarás con Leadership, Agile, Hiring en proyectos de alto impacto.',
    publishedAt: '2025-12-03T11:41:00.000Z',
    tags: ['Leadership', 'Agile', 'Hiring'],
  },
  {
    id: 'job-85',
    title: 'Machine Learning Engineer Staff',
    company: 'Mercado Libre',
    city: 'Querétaro',
    salary: null,
    description:
      'Buscamos Machine Learning Engineer Staff para unirse al equipo de Mercado Libre en Querétaro. Trabajarás con Python, TensorFlow, ML en proyectos de alto impacto.',
    publishedAt: '2026-01-04T12:48:00.000Z',
    tags: ['Python', 'TensorFlow', 'ML'],
  },
  {
    id: 'job-86',
    title: 'Cloud Architect',
    company: 'Softtek',
    city: 'Tijuana',
    salary: 35000,
    description:
      'Buscamos Cloud Architect para unirse al equipo de Softtek en Tijuana. Trabajarás con AWS, Azure, Architecture en proyectos de alto impacto.',
    publishedAt: '2026-02-05T13:55:00.000Z',
    tags: ['AWS', 'Azure', 'Architecture'],
  },
  {
    id: 'job-87',
    title: 'Security Engineer Jr',
    company: 'Globant',
    city: 'Mérida',
    salary: 145000,
    description:
      'Buscamos Security Engineer Jr para unirse al equipo de Globant en Mérida. Trabajarás con Security, Pentesting, IAM en proyectos de alto impacto.',
    publishedAt: '2026-03-06T14:02:00.000Z',
    tags: ['Security', 'Pentesting', 'IAM'],
  },
  {
    id: 'job-88',
    title: 'Site Reliability Engineer Semi Senior',
    company: 'Wizeline',
    city: 'León',
    salary: 125000,
    description:
      'Buscamos Site Reliability Engineer Semi Senior para unirse al equipo de Wizeline en León. Trabajarás con SRE, Monitoring, Kubernetes en proyectos de alto impacto.',
    publishedAt: '2026-04-07T15:09:00.000Z',
    tags: ['SRE', 'Monitoring', 'Kubernetes'],
  },
  {
    id: 'job-89',
    title: 'Technical Lead Senior',
    company: 'Belatrix',
    city: 'Cancún',
    salary: 120000,
    description:
      'Buscamos Technical Lead Senior para unirse al equipo de Belatrix en Cancún. Trabajarás con Leadership, React, Node.js en proyectos de alto impacto.',
    publishedAt: '2026-05-08T16:16:00.000Z',
    tags: ['Leadership', 'React', 'Node.js'],
  },
  {
    id: 'job-90',
    title: 'Data Scientist Staff',
    company: 'Encora',
    city: 'Remoto',
    salary: 155000,
    description:
      'Buscamos Data Scientist Staff para unirse al equipo de Encora en Remoto. Trabajarás con Python, Statistics, ML en proyectos de alto impacto.',
    publishedAt: '2026-06-09T17:23:00.000Z',
    tags: ['Python', 'Statistics', 'ML'],
  },
  {
    id: 'job-91',
    title: 'React Native Developer',
    company: 'OCC Mundial',
    city: 'Ciudad de México',
    salary: null,
    description:
      'Buscamos React Native Developer para unirse al equipo de OCC Mundial en Ciudad de México. Trabajarás con React Native, TypeScript, Mobile en proyectos de alto impacto.',
    publishedAt: '2025-09-10T18:30:00.000Z',
    tags: ['React Native', 'TypeScript', 'Mobile'],
  },
  {
    id: 'job-92',
    title: 'Frontend Engineer Jr',
    company: 'Nubank MX',
    city: 'Guadalajara',
    salary: 150000,
    description:
      'Buscamos Frontend Engineer Jr para unirse al equipo de Nubank MX en Guadalajara. Trabajarás con React, TypeScript, CSS en proyectos de alto impacto.',
    publishedAt: '2025-10-11T19:37:00.000Z',
    tags: ['React', 'TypeScript', 'CSS'],
  },
  {
    id: 'job-93',
    title: 'Backend Engineer Semi Senior',
    company: 'Kavak',
    city: 'Monterrey',
    salary: 95000,
    description:
      'Buscamos Backend Engineer Semi Senior para unirse al equipo de Kavak en Monterrey. Trabajarás con Node.js, Express, PostgreSQL en proyectos de alto impacto.',
    publishedAt: '2025-11-12T20:44:00.000Z',
    tags: ['Node.js', 'Express', 'PostgreSQL'],
  },
  {
    id: 'job-94',
    title: 'Full Stack Developer Senior',
    company: 'Bitso',
    city: 'Puebla',
    salary: 100000,
    description:
      'Buscamos Full Stack Developer Senior para unirse al equipo de Bitso en Puebla. Trabajarás con React, Node.js, TypeScript en proyectos de alto impacto.',
    publishedAt: '2025-12-13T21:51:00.000Z',
    tags: ['React', 'Node.js', 'TypeScript'],
  },
  {
    id: 'job-95',
    title: 'Mobile Engineer iOS Staff',
    company: 'Clip',
    city: 'Querétaro',
    salary: 25000,
    description:
      'Buscamos Mobile Engineer iOS Staff para unirse al equipo de Clip en Querétaro. Trabajarás con Swift, iOS, Mobile en proyectos de alto impacto.',
    publishedAt: '2026-01-14T22:58:00.000Z',
    tags: ['Swift', 'iOS', 'Mobile'],
  },
  {
    id: 'job-96',
    title: 'Mobile Engineer Android',
    company: 'Konfío',
    city: 'Tijuana',
    salary: 155000,
    description:
      'Buscamos Mobile Engineer Android para unirse al equipo de Konfío en Tijuana. Trabajarás con Kotlin, Android, Mobile en proyectos de alto impacto.',
    publishedAt: '2026-02-15T23:05:00.000Z',
    tags: ['Kotlin', 'Android', 'Mobile'],
  },
]
